### ISSUE TITLE
Door locks not showing under entities.

### ISSUE THREAD

**Issue by jthorell90** [karlenek/hasscontrol#10]
First of all, great work. I can’t give enough credits to people that dedicate time and effort to make life a lot simpler for us that have very limited programming skills.

I have two issues with HassControl.
*Token does not seem to work. It simply failed to authenticate.
Found a work around by using login instead.

*I can't get the widget to show door lock entities.
For testing purposes I’ve created three groups.
One that contains two light entities, and one that contain two door lock entities, and one that contains two lights and two door lock entities.

My configuration.yaml look like this:
```
group:
  doors:
    name: Door Lock
    entities:
      - lock.stue_door_locked
      - lock.yttergang_door_locked
  lights:
    name: light
    entities:
      - light.kjokken_downlights_instance_1_level
      - light.kjokken_benklys_instance_1_level
  Doors-and-lights:
    name: Doors and lights
    entities:
      - lock.stue_door_locked
      - lock.yttergang_door_locked
      - light.kjokken_downlights_instance_1_level
      - light.kjokken_benklys_instance_1_level

```

After installing and configurating the widget I’ve added one group at the time before refreshing from the widget menu.
*If I use group.doors, it show no entities.
*If I use group.lights, it shows both light entities.
*If I use group.doors_and_lights, it shows both light entities.

I have also tested all three groups in the lovelace GUI and door locks show up just as expected.

Don’t HassControl support lock entities?

 
My lock entites in HA look like this:
![doorlocks](https://user-images.githubusercontent.com/46829043/106204856-eabe8600-61bd-11eb-9fc2-6394a970d227.png)
